algoritmo "Creuza02"
// ================================================================
// Creuza vai viajar e precisa converter seus reais para dólares
// ================================================================
var
   reais, dolares: Real
inicio
      escreva("Quantos reais eu tenho? ")
      leia(reais)
      dolares <- reais/5.12
      escreva("Posso comprar US$", dolares)
fimalgoritmo