algoritmo "valores"
// ================================================================
// Solicitar dois números para o usuário mostrar a soma entre eles.
// ================================================================
var
   N1, N2, S:
inicio
      escreva("Informe um número: ")
      leia(N1)
      escreva("Informe outro número: ")
      leia(N2)
      S <- N1 + N2
      escreva("A soma entre ", N1, " e ", N2, " é igual a ", S)
fimalgoritmo