algoritmo "ConteAte10"
// ============================================================
// Contar de 0 até 10
// ============================================================
var
   contador: Inteiro
inicio
      contador <- 0
      Enquanto (contador <= 10) faca
               Escreval(contador)
               contador <- contador + 1
      FimEnquanto
      Escreval("Terminei de contar")
fimalgoritmo
