algoritmo "ConteAte0"
// ================================================================
// Contar de 10 até 0
// ================================================================
var
   contador: Inteiro
inicio
      contador <- 10
      enquanto (contador >= 0) faca
               escreval(contador)
               contador <- contador - 1
      fimenquanto
      escreval("Terminei de contar")
fimalgoritmo