algoritmo "ConteAte0"
// ===============================================================
// Contar de 10 até 0
// ===============================================================
var
   contador: Inteiro
inicio
      contador <- 10
      Enquanto (contador >= 0) faca
               Escreval(contador)
               contador <- contador - 1
      FimEnquanto
      Escreval("Terminei de contar")
fimalgoritmo
