algoritmo "ConteAte10"
// ================================================================
// Contar de 0 até 10
// ================================================================
var
   contador: Inteiro
inicio
      contador <- 0
      enquanto (contador <= 10) faca
               escreval(contador)
               contador <- contador + 1
      fimenquanto
      escreval("Terminei de contar")
fimalgoritmo