algoritmo "desafio001"
// ==================================================================
// Escreva um programa que mostre na tela a mensagem "Olá, Mundo!"
//
// AUTOR: João Paulo Pinheiro do Nascimento
// Exercícios Resolvidos do Curso Em Video - Profº: Gustavo Guanabara
// ==================================================================
var
inicio
   escreval("+---------==== R E S U L T A D O ====---------+")
   escreval
   escreval("Olá, Mundo!")
fimalgoritmo