algoritmo "Creuza02"
// ====================================================================
// Creuza vai viajar e precisa converter seus reais para dólares
// ====================================================================
var
   reais, dolares: Real
inicio
      Escreva("Quantos reais eu tenho? ")
      Leia(reais)
      dolares <- reais/5.12
      Escreva("Posso comprar US$", dolares)
fimalgoritmo
